<?php
/**
 * ------------------------ 
 *  版权所有  www.tecmz.com
 *  商业版本请购买正版授权使用
 * ------------------------
*/ namespace Module\Member\Admin\Controller; use Illuminate\Routing\Controller; use ModStart\Admin\Concern\HasAdminQuickCRUD; use ModStart\Admin\Layout\AdminConfigBuilder; use ModStart\Admin\Layout\AdminCRUDBuilder; use ModStart\Core\Dao\ModelUtil; use ModStart\Form\Form; use ModStart\Grid\GridFilter; use ModStart\Module\ModuleManager; use ModStart\Support\Concern\HasFields; use Module\Member\Biz\Vip\MemberVipBiz; use Module\Member\Util\MemberVipUtil; class MemberVipSetController extends Controller { use HasAdminQuickCRUD; protected function crud(AdminCRUDBuilder $UXxZR) { $UXxZR->init('member_vip_set')->field(function ($UXxZR) { $UXxZR->layoutPanel('基础信息', function ($UXxZR) { $UXxZR->id('id', 'ID')->addable(true)->editable(true)->ruleUnique('member_vip_set')->required()->defaultValue(ModelUtil::sortNext('member_vip_set', array(), 'id')); $UXxZR->text('title', '名称')->required()->ruleUnique('member_vip_set'); $UXxZR->text('flag', '英文标识')->required()->ruleUnique('member_vip_set'); $UXxZR->switch('visible', '可见')->gridEditable(true)->tip('开启后前台用户VIP开通页面可见'); $UXxZR->switch('isDefault', '默认')->optionsYesNo()->help('会员是否默认为该等级')->required(); $UXxZR->image('icon', '图标'); $UXxZR->currency('price', '价格')->required(); $UXxZR->number('vipDays', '时间')->required()->help('单位为天，365表示1年'); $UXxZR->text('desc', '简要说明')->required(); $UXxZR->richHtml('content', '详细说明')->required(); if (ModuleManager::getModuleConfig('Member', 'creditEnable', false)) { $UXxZR->switch('creditPresentEnable', '赠送积分')->when('=', true, function ($GtTXi) { $GtTXi->number('creditPresentValue', '赠送积分数量'); })->optionsYesNo()->listable(false); } }); foreach (MemberVipBiz::all() as $strQF) { $UXxZR->layoutPanel($strQF->title(), function ($UXxZR) use($strQF) { $strQF->vipField($UXxZR); }); } $UXxZR->display('created_at', L('Created At'))->listable(false); $UXxZR->display('updated_at', L('Updated At'))->listable(false); })->gridFilter(function (GridFilter $UGzyw) { $UGzyw->like('title', '名称'); })->gridOperateAppend('
<a href="javascript:;" class="btn btn-primary" data-dialog-width="90%" data-dialog-height="90%" data-dialog-request="' . modstart_admin_url('member_vip_set/config') . '">
    <i class="iconfont icon-cog"></i>
    功能设置
</a>
<a href="javascript:;" class="btn btn-primary" data-dialog-width="90%" data-dialog-height="90%" data-dialog-request="' . modstart_admin_url('member_vip_right') . '">
    <i class="iconfont icon-cube"></i>
    权益设置
</a>
')->operateFixed('right')->enablePagination(false)->defaultOrder(array('sort', 'asc'))->canSort(true)->canShow(false)->title('用户VIP等级')->addDialogSize(array('600px', '95%'))->editDialogSize(array('600px', '95%'))->hookSaved(function (Form $GtTXi) { MemberVipUtil::clearCache(); }); } public function config(AdminConfigBuilder $UXxZR) { goto TL30z; hGRI1: $UXxZR->pageTitle('功能设置'); goto qo59X; TL30z: $UXxZR->useDialog(); goto hGRI1; qo59X: $UXxZR->richHtml('Member_VipContent', 'VIP开通说明')->help('默认为 VIP开通说明'); goto GiR0y; N8QI2: return $UXxZR->perform(); goto iOSrj; GiR0y: $UXxZR->formClass('wide'); goto N8QI2; iOSrj: } }